# Generated by Django 5.2.5 on 2025-08-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='evilcat.png', upload_to=''),
        ),
    ]
