# Generated by Django 5.2.5 on 2025-09-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowApp', '0003_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=140),
        ),
    ]
